apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfoug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfoug
  template:
    metadata:
      labels:
        app: dfoug
    spec:
      containers:
      - image: okteto.dev/dfoug:latest
        name: dfoug
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "80097c61-7f54-408a-b32e-8f61e3506d92"
        - name: Vless_Path
          value: "/vl5hh255"
        - name: Vmess_UUID
          value: "80097c61-7f54-408a-b32e-8f61e3506d92"
        - name: Vmess_Path
          value: "/vm6dd566"
        - name: Share_Path
          value: "/v2link"
